
import { CharacterData } from './types';

export const INITIAL_CHARACTERS: CharacterData[] = [
  {
    id: 0,
    key: "goku",
    name: "Goku",
    price: 0,
    unlocked: true,
    maxHp: 220,
    transformAvailable: true,
    sprite: "assets/sprites/goku_spritesheet.png",
    frameWidth: 64,
    frameHeight: 64,
    specialName: "KAMEHAMEHA",
    superName: "GENKIDAMA",
    specialColor: 0x00ffff
  },
  {
    id: 1,
    key: "vegeta",
    name: "Vegeta",
    price: 0,
    unlocked: true,
    maxHp: 210,
    transformAvailable: true,
    sprite: "assets/sprites/vegeta_spritesheet.png",
    frameWidth: 64,
    frameHeight: 64,
    specialName: "GALICK GUN",
    superName: "FINAL FLASH",
    specialColor: 0x9b59b6
  },
  {
    id: 2,
    key: "gohan",
    name: "Gohan",
    price: 300,
    unlocked: true,
    maxHp: 200,
    transformAvailable: true,
    sprite: "assets/sprites/gohan_spritesheet.png",
    frameWidth: 64,
    frameHeight: 64,
    specialName: "MASENKO",
    superName: "FATHER-SON KAMEHAMEHA",
    specialColor: 0xffff00
  },
  {
    id: 3,
    key: "piccolo",
    name: "Piccolo",
    price: 300,
    unlocked: true,
    maxHp: 230,
    transformAvailable: true,
    sprite: "assets/sprites/piccolo_spritesheet.png",
    frameWidth: 64,
    frameHeight: 64,
    specialName: "MAKANKOSAPPO",
    superName: "HELLZONE GRENADE",
    specialColor: 0xffff00
  },
  {
    id: 18,
    key: "madara",
    name: "Madara Uchiha",
    price: 2600,
    unlocked: true,
    maxHp: 270,
    transformAvailable: true, // Susanoo
    sprite: "",
    frameWidth: 64,
    frameHeight: 64,
    specialName: "MAJESTIC DESTROYER FLAME",
    superName: "TENGAI SHINSEI", // Meteor
    specialColor: 0xff4500
  },
  {
    id: 5,
    key: "cell",
    name: "Cell",
    price: 550,
    unlocked: false,
    maxHp: 240,
    transformAvailable: true,
    sprite: "",
    frameWidth: 64,
    frameHeight: 64,
    specialName: "KAMEHAMEHA",
    superName: "SOLAR KAMEHAMEHA",
    specialColor: 0x00ff00
  },
  {
    id: 6,
    key: "leonardo",
    name: "Leonardo",
    price: 600,
    unlocked: false,
    maxHp: 210,
    transformAvailable: false,
    sprite: "",
    frameWidth: 64,
    frameHeight: 64,
    specialName: "KATANA SLASH",
    superName: "NINJA BARRAGE",
    specialColor: 0x3498db
  },
  {
    id: 7,
    key: "frieren",
    name: "Frieren",
    price: 700,
    unlocked: false,
    maxHp: 215,
    transformAvailable: true, // Mana Unleashed Mode
    sprite: "",
    frameWidth: 64,
    frameHeight: 64,
    specialName: "ZOLTRAAK",
    superName: "BLACK HOLE",
    specialColor: 0xdfe6e9 // White/Silver Energy
  },
  {
    id: 8,
    key: "optimus",
    name: "Optimus Prime",
    price: 800,
    unlocked: true,
    maxHp: 250,
    transformAvailable: true, // Truck Mode
    sprite: "",
    frameWidth: 64,
    frameHeight: 64,
    specialName: "MISSILE STRIKE",
    superName: "MATRIX BLAST",
    specialColor: 0xff6b6b
  },
  {
    id: 9,
    key: "minipekka",
    name: "Mini P.E.K.K.A",
    price: 900,
    unlocked: false,
    maxHp: 230,
    transformAvailable: true, // Rage Mode
    sprite: "",
    frameWidth: 64,
    frameHeight: 64,
    specialName: "PANCAKES",
    superName: "MEGA PANCAKE",
    specialColor: 0x00aaff
  },
  {
    id: 10,
    key: "cyberninja",
    name: "Cyber Zero",
    price: 1000,
    unlocked: true,
    maxHp: 200,
    transformAvailable: true, // Overdrive Mode
    sprite: "",
    frameWidth: 64,
    frameHeight: 64,
    specialName: "PLASMA DASH",
    superName: "CYBER OVERDRIVE",
    specialColor: 0x00eaff
  },
  {
    id: 11,
    key: "chapolim",
    name: "Chapolim",
    price: 1200,
    unlocked: true,
    maxHp: 180,
    transformAvailable: false,
    sprite: "",
    frameWidth: 64,
    frameHeight: 64,
    specialName: "CHIPOTE CHILLÓN",
    superName: "AEROLITOS",
    specialColor: 0xff0000
  },
  {
    id: 12,
    key: "naruto",
    name: "Naruto",
    price: 1500,
    unlocked: true,
    maxHp: 220,
    transformAvailable: true,
    sprite: "",
    frameWidth: 64,
    frameHeight: 64,
    specialName: "RASENGAN",
    superName: "RASENSHURIKEN",
    specialColor: 0x3498db
  },
  {
    id: 13,
    key: "batman",
    name: "Batman",
    price: 1800,
    unlocked: true,
    maxHp: 240,
    transformAvailable: true,
    sprite: "",
    frameWidth: 64,
    frameHeight: 64,
    specialName: "BATARANG",
    superName: "THE DARK KNIGHT",
    specialColor: 0x34495e
  },
  {
    id: 14,
    key: "thukuna",
    name: "Thukuna",
    price: 2000,
    unlocked: true,
    maxHp: 260,
    transformAvailable: true,
    sprite: "",
    frameWidth: 64,
    frameHeight: 64,
    specialName: "CLEAVE",
    superName: "CASTELO MANIVOLENTE",
    specialColor: 0x8b0000
  },
  {
    id: 15,
    key: "gojo",
    name: "Satoru Gojo",
    price: 2500,
    unlocked: true,
    maxHp: 280,
    transformAvailable: true,
    sprite: "",
    frameWidth: 64,
    frameHeight: 64,
    specialName: "RED & BLUE",
    superName: "HOLLOW PURPLE",
    specialColor: 0x8a2be2
  },
  {
    id: 16,
    key: "obito",
    name: "Obito Uchiha",
    price: 2200,
    unlocked: true,
    maxHp: 230,
    transformAvailable: true, // Ten-Tails Jinchuriki mode
    sprite: "",
    frameWidth: 64,
    frameHeight: 64,
    specialName: "KAMUI",
    superName: "TEN-TAILS BEAST BOMB",
    specialColor: 0xff4500 // Orange-red
  },
  {
    id: 19,
    key: "itachi",
    name: "Itachi Uchiha",
    price: 2400,
    unlocked: true,
    maxHp: 210,
    transformAvailable: true,
    sprite: "",
    frameWidth: 64,
    frameHeight: 64,
    specialName: "AMATERASU",
    superName: "TSUKUYOMI",
    specialColor: 0x000000
  },
  {
    id: 20,
    key: "jotaro",
    name: "Jotaro Kujo",
    price: 2000,
    unlocked: true,
    maxHp: 250,
    transformAvailable: true,
    sprite: "",
    frameWidth: 64,
    frameHeight: 64,
    specialName: "STAR FINGER",
    superName: "ORA ORA ORA",
    specialColor: 0x8a2be2
  },
  {
    id: 17,
    key: "spiderman",
    name: "Spider-Man",
    price: 1900,
    unlocked: true,
    maxHp: 240,
    transformAvailable: true,
    sprite: "",
    frameWidth: 64,
    frameHeight: 64,
    specialName: "WEB SHOOTER",
    superName: "MAXIMUM SPIDER",
    specialColor: 0xffffff
  },
  {
    id: 21,
    key: "saitama",
    name: "Saitama",
    price: 3000,
    unlocked: true,
    maxHp: 350,
    transformAvailable: true, // Serious Mode
    sprite: "",
    frameWidth: 64,
    frameHeight: 64,
    specialName: "SERIOUS PUNCH",
    superName: "SUPREME HEADBUTT",
    specialColor: 0xffcc00
  }
];
